---
title: Demo Site
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: projects
  values:
    layout: default
email: esty.mediaotg@gmail.com
description: 'This is just a demo website to figure out jekyll

'
baseurl: ''
url: http://yourdomain.com
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
