---
title: Demo Site
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: projects
  values:
    layout: default
    Info:
      address:
      square feet:
      stories:
      residential_units:
     commercial_units:
    Date:
      is_complete: 
      complete_date: 
email: esty.mediaotg@gmail.com
description: 'This is just a demo website to figure out jekyll

'
baseurl: ''
url: http://yourdomain.com
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
