---
title: Demo Site
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: esty.mediaotg@gmail.com
description: 'This is just a demo website to figure out jekyll

'
baseurl: ''
url: http://yourdomain.com
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      colors: ["red", "green", "blue"]
